# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AcmeForAppliances < Formula
  desc "ACME Support for appliances that don't natively support it"
  homepage "https://github.com/beryju/acme-for-appliances"
  version "1.1.2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/BeryJu/acme-for-appliances/releases/download/v1.1.2/acme-for-appliances_1.1.2_darwin_arm64.tar.gz"
      sha256 "0aaa573e9d81a3c87410e73e21e12970b5434e4155e93982a187d0986f35d025"
    end
    if Hardware::CPU.intel?
      url "https://github.com/BeryJu/acme-for-appliances/releases/download/v1.1.2/acme-for-appliances_1.1.2_darwin_amd64.tar.gz"
      sha256 "f18e25e8a7d3dd64a86ce76d1963eca86877af086e3d416daf630f7365376b6a"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/BeryJu/acme-for-appliances/releases/download/v1.1.2/acme-for-appliances_1.1.2_linux_arm.tar.gz"
      sha256 "b2035e83edcc164b412f85c1a3fb2d2cefcc5f00abed6fa844a5f4b6e8c119b0"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BeryJu/acme-for-appliances/releases/download/v1.1.2/acme-for-appliances_1.1.2_linux_arm64.tar.gz"
      sha256 "912657e172efa48b0e69b16d6cc89fa4f5f07df6d3314021033474559a10c9d6"
    end
    if Hardware::CPU.intel?
      url "https://github.com/BeryJu/acme-for-appliances/releases/download/v1.1.2/acme-for-appliances_1.1.2_linux_amd64.tar.gz"
      sha256 "037c4da5a2cb277f1b995b5d31d19249db7e9500bf790ea63c9edb0501d1311e"
    end
  end

  def install
    bin.install "acme-for-appliances"
  end
end
