# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AcmeForAppliances < Formula
  desc "ACME Support for appliances that don't natively support it"
  homepage "https://github.com/beryju/acme-for-appliances"
  version "1.0.2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/BeryJu/acme-for-appliances/releases/download/v1.0.2/acme-for-appliances_1.0.2_darwin_amd64.tar.gz"
      sha256 "2418a578bc4beeeed7eacd8584772c9050de9fc7dacb84163ea88915eb847e90"
    end
    if Hardware::CPU.arm?
      url "https://github.com/BeryJu/acme-for-appliances/releases/download/v1.0.2/acme-for-appliances_1.0.2_darwin_arm64.tar.gz"
      sha256 "a548fed18248db055ffe70e74d32f1b75cb43da34cc319bf65b15394c6f42aef"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/BeryJu/acme-for-appliances/releases/download/v1.0.2/acme-for-appliances_1.0.2_linux_amd64.tar.gz"
      sha256 "70d4f556b05b8cd9dd1d2f003bce363f170e7ca67d9cf68679a36dab5158aaa8"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/BeryJu/acme-for-appliances/releases/download/v1.0.2/acme-for-appliances_1.0.2_linux_arm.tar.gz"
      sha256 "7ffffdc112d683dd4cdde2408fc29c8e07864d85f7015cc35b8fec0acd8a4878"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BeryJu/acme-for-appliances/releases/download/v1.0.2/acme-for-appliances_1.0.2_linux_arm64.tar.gz"
      sha256 "2508cc238e89123ed8f4e46839cb34c710d6b83ce689ab40deffb1ec8b871b7f"
    end
  end

  def install
    bin.install "acme-for-appliances"
  end
end
