# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Korb < Formula
  desc "Move Kubernetes PVCs between Storage Classes and Namespaces"
  homepage "https://github.com/beryju/korb"
  version "2.1.2"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/BeryJu/korb/releases/download/v2.1.2/korb_darwin_arm64"
      sha256 "e870fae1ed4b97034a27775b645fa66568d5ea4bd68113b88c8cefd49512b0d5"

      def install
        bin.install "korb_darwin_arm64" => "korb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/BeryJu/korb/releases/download/v2.1.2/korb_darwin_amd64"
      sha256 "6ae3456cc88df9785c6b44519eea4db6d531c20ab8c66ca9be747c36af5ef03b"

      def install
        bin.install "korb_darwin_amd64" => "korb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/BeryJu/korb/releases/download/v2.1.2/korb_linux_arm"
      sha256 "64f9900a6bdbdd648c93b716282fda3a14d6c754f59fee1f12cc32cbc5bd6040"

      def install
        bin.install "korb_linux_arm" => "korb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BeryJu/korb/releases/download/v2.1.2/korb_linux_arm64"
      sha256 "0f0fc474cb00284e9dad5161c36f241c6d24e9b70fd09334b80756c889ef6355"

      def install
        bin.install "korb_linux_arm64" => "korb"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/BeryJu/korb/releases/download/v2.1.2/korb_linux_amd64"
      sha256 "59e9ae2298e2603e834ec4ae673e83d467c0879e8a09aa91ce407525eed5d305"

      def install
        bin.install "korb_linux_amd64" => "korb"
      end
    end
  end
end
