# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class OidcTestClient < Formula
  desc "This is a small, golang-based OIDC Client, to be used in End-to-end or other testing."
  homepage "https://github.com/beryju/oidc-test-client"
  version "1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/BeryJu/oidc-test-client/releases/download/v1.0/oidc-test-client_darwin_amd64"
      sha256 "b7e2e7b7b0a903b7d940d5e39444403077492745b123a9df911ced3e7ac1bcd8"

      def install
        bin.install "oidc-test-client_darwin_amd64" => "oidc-test-client"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/BeryJu/oidc-test-client/releases/download/v1.0/oidc-test-client_darwin_arm64"
      sha256 "c393082cae6edf0c06f980dc425cb70d07de0270c7183f257389a7d04f9b999c"

      def install
        bin.install "oidc-test-client_darwin_arm64" => "oidc-test-client"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BeryJu/oidc-test-client/releases/download/v1.0/oidc-test-client_linux_arm64"
      sha256 "a067a2c2a5cfe4f8d467b8935d1de5a1a513524df5e921c4b13336e5dc1d954a"

      def install
        bin.install "oidc-test-client_linux_arm64" => "oidc-test-client"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/BeryJu/oidc-test-client/releases/download/v1.0/oidc-test-client_linux_armv6"
      sha256 "4fab347c1d8b2c063bf8619d2626edf7063767bd7ccc3e59882c08f74f38e43c"

      def install
        bin.install "oidc-test-client_linux_armv6" => "oidc-test-client"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/BeryJu/oidc-test-client/releases/download/v1.0/oidc-test-client_linux_amd64"
      sha256 "5ca70b3c8568f90c887275b5dc35b3bdc4951608aceb11b1c3883e40a4088c27"

      def install
        bin.install "oidc-test-client_linux_amd64" => "oidc-test-client"
      end
    end
  end
end
