# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SamlTestSp < Formula
  desc "Small, SAML ServiceProvider for testing and debugging"
  homepage "https://github.com/beryju/saml-test-sp"
  version "1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/BeryJu/saml-test-sp/releases/download/v1.1/saml-test-sp_darwin_amd64"
      sha256 "ffee09f547c49317f45f308ee9a0502867735b9f1bae76014c985ff3b9fa85ea"

      def install
        bin.install "saml-test-sp_darwin_amd64" => "saml-test-sp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/BeryJu/saml-test-sp/releases/download/v1.1/saml-test-sp_darwin_arm64"
      sha256 "24ed8304e5503afa7a42552a4e85478e492a6a9c20fc716625fd9d83286ab03f"

      def install
        bin.install "saml-test-sp_darwin_arm64" => "saml-test-sp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/BeryJu/saml-test-sp/releases/download/v1.1/saml-test-sp_linux_armv6"
      sha256 "0a2092f0e93721b9171270a3b9b22cbb56a3d53eb7d7184f4e7942440a90e4de"

      def install
        bin.install "saml-test-sp_linux_armv6" => "saml-test-sp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/BeryJu/saml-test-sp/releases/download/v1.1/saml-test-sp_linux_amd64"
      sha256 "3b5cb03e8b2128ef80a4c52bbcce40f107625d5bd97c582225b333ce45ba6378"

      def install
        bin.install "saml-test-sp_linux_amd64" => "saml-test-sp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BeryJu/saml-test-sp/releases/download/v1.1/saml-test-sp_linux_arm64"
      sha256 "6ffb688d9a481690e0908e8f22cdd677ae85d50eb6609d7960abc89af5e5cf25"

      def install
        bin.install "saml-test-sp_linux_arm64" => "saml-test-sp"
      end
    end
  end
end
