# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SamlTestSp < Formula
  desc "A small, SAML ServiceProvider for testing and debugging"
  homepage "https://github.com/beryju/saml-test-sp"
  version "1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/BeryJu/saml-test-sp/releases/download/v1.0/saml-test-sp_darwin_arm64"
      sha256 "ab11278e5af5898d44a8d3545a26bd12415507a1ebdf87e5cb33c5e860922d3a"

      def install
        bin.install "saml-test-sp_darwin_arm64" => "saml-test-sp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/BeryJu/saml-test-sp/releases/download/v1.0/saml-test-sp_darwin_amd64"
      sha256 "c5ceb6c1feb749e0cbdf1b951566d5bcc6433474863c789e47255b6739c59a67"

      def install
        bin.install "saml-test-sp_darwin_amd64" => "saml-test-sp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/BeryJu/saml-test-sp/releases/download/v1.0/saml-test-sp_linux_armv6"
      sha256 "4103a96ac08c372c8c5eb7110e616b1adc8bedee314f03365b85abbc824a8a7f"

      def install
        bin.install "saml-test-sp_linux_armv6" => "saml-test-sp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/BeryJu/saml-test-sp/releases/download/v1.0/saml-test-sp_linux_arm64"
      sha256 "9156d365d6ab7f9349f083a591ef618ca1b1d3c5cc91d703ff047cf75b2b1e7e"

      def install
        bin.install "saml-test-sp_linux_arm64" => "saml-test-sp"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/BeryJu/saml-test-sp/releases/download/v1.0/saml-test-sp_linux_amd64"
      sha256 "74d88868cf1c8e7e19aa2467a57880eae4a35500cffeb72c3a03636a84db260e"

      def install
        bin.install "saml-test-sp_linux_amd64" => "saml-test-sp"
      end
    end
  end
end
